-- liquibase formatted sql

-- changeset vadimgupal:2
CREATE TABLE IF NOT EXISTS authors
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
--rollback DROP TABLE IF EXISTS authors;