-- liquibase formatted sql

-- changeset vadimgupal:1
CREATE TABLE IF NOT EXISTS books
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);
--rollback DROP TABLE IF EXISTS books;